clc;clear all;close all;
lgndsize=14;labsize=15;txtsize=16;arrowwidth=1;linsize=1.5;NameFont='Cambria';

pi=3.1415926535;
theta=45*pi/180;              %%rad
c=299792458;                  %%m/s
d=linspace(1,6000,1000);        %%10^9 m : Pluto is 5 900 898 440 km away
S=10000;                      %%m2

phi=(5535.8./d).^2;             %%W/m2
T=2*sin(theta)*S*phi/c;       %%N

figure;hold on;
plot(d/150,T,'k','LineWidth',1.5);

title(['Thrust generated by a  ',num2str(S),' m^2 solar sail (N)']);
xlabel('Distance to the Sun (ua)');
ylabel('Thrust (N)');
box on;axis tight;grid on;
set(gca,'fontsize', lgndsize,'FontWeight','normal','FontName',NameFont,'YScale', 'log');


plot(57.91/150, T(11), 'color','#808080','Marker', '.','markersize',15);
plot(108.2/150, T(20), 'color', '#d3a873','Marker', '.','markersize',25);
plot(149.6/150, T(26), 'color', '#3866ff','Marker', '.', 'markersize',25);
plot(227.9/150, T(39), 'color', 'r','Marker', '.','markersize',20);
plot(778.3/150, T(132), 'color','#ff9a3e','Marker', '.','markersize',75);
plot(1426/150, T(240), 'color', '#ffbf3e','Marker','.', 'markersize',60);
plot(2870/150, T(470), 'color', 'c','Marker','.','markersize',45);
plot(4498/150, T(745), 'color', '#3e2efa','Marker','.','markersize',45);
plot(5900/150, T(979), 'color', '#808080','Marker','.','markersize',15);
